allowBuilds:
  '@google/genai': set this to true or false
  protobufjs: set this to true or false
  react-tsparticles: set this to true or false
  tsparticles-engine: set this to true or false
  unrs-resolver: set this to true or false
